apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guarantee-explorer-ing
  namespace: fabric
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod-issuer
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: guarantee-explorer-crt
    hosts:
    - fabric-explorer.blockchain.foundery.club
  rules:
  - host: fabric-explorer.blockchain.foundery.club
    http:
      paths:
      - path: /
        backend:
          serviceName: fabric-explorer-svc
          servicePort: 8080